stages:
  - build
  - run
  - test
  - bench
  - document

before_script:
  - bash setup.sh
  - rustup --version
  - rustc --version
  - cargo --version
  #- cargo +nightly fmt --version
  #- sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # Leave node-replication alone for the moment:
  - sed -i'' -e '/git@github.com:gz\/node-replication.git/!s/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - cd kernel
    - RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build -v --target=x86_64-bespin -Zfeatures=all
  variables:
    GIT_STRATEGY: fetch

run-qemu:
  stage: run
  script:
    - cd kernel
    - python3 run.py --cmd log=trace
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

run-unix:
  stage: run
  script:
    - cd kernel
    - cargo run
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

test:
  stage: test
  script:
    - cd lib/slabmalloc
    - cargo test
    - cd ../../kernel
    - cargo +nightly fmt --package bespin -- --check
    - RUST_TEST_THREADS=1 cargo test --features smoke
    - cd ..
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

bench:
  stage: bench
  script:
    - cd kernel
    - RUST_TEST_THREADS=1 cargo test --test integration-test -- s06_vmops_benchmark
    - cd ..
  dependencies:
    - test
  variables:
    GIT_STRATEGY: fetch

pages:
  stage: document
  script:
    - source ~/.cargo/env
    - cd doc
    - mdbook build -d ../book
    - cd ..
    - git clone bespin-gh-pages:gz/bespin gh-pages
    - cd gh-pages
    - git checkout gh-pages
    - rm -rf ./book
    - mv ../book ./
    - git add .
    - git commit -a -m "Added documentation."
    - git push origin gh-pages
    - cd ..
    - rm -rf gh-pages/ book/
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  only: ['master']
