stages:
  - build
  - run
  - test
  - bench
  - document

before_script:
  # Add SSH key
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - echo "$SSH_PRIVATE_KEY_NR" | tr -d '\r' | ssh-add -
  - bash setup.sh
  - rustup --version
  - rustc --version
  - cargo --version
  #- cargo +nightly fmt --version
  #- sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  # Leave node-replication alone for the moment:
  - sed -i'' -e '/git@github.com:gz\/node-replication.git/!s/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - cd kernel
    - RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build -v --target=x86_64-bespin -Zfeatures=all
  variables:
    GIT_STRATEGY: fetch

run-qemu:
  stage: run
  script:
    - cd kernel
    - python3 run.py --cmd log=trace
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

run-unix:
  stage: run
  script:
    - cd kernel
    - cargo run
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

test:
  stage: test
  script:
    - cd lib/slabmalloc
    - cargo test
    - cd ../../kernel
    - cargo +nightly fmt --package bespin -- --check
    - RUST_TEST_THREADS=1 cargo test --features smoke
    - cd ..
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

benchmark:skylake2x:
  stage: bench
  script:
    - bash scripts/ci.bash
  dependencies:
    - test
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake2x

benchmark:skylake4x:
  stage: bench
  script:
    - bash scripts/ci.bash
  dependencies:
    - test
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake4x

docs:
  stage: document
  script:
    - source ~/.cargo/env
    - cd doc
    - mdbook build -d ../book
    - cd ..
    - git clone -b gh-pages git@github.com:gz/bespin.git gh-pages
    - cd gh-pages
    - rm -rf ./book
    - mv ../book ./
    - git add .
    - git commit -a -m "Added documentation." || true
    - git push origin gh-pages || true
    - cd ..
    - rm -rf gh-pages/ book/
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch
  only: ['master']
