language: rust
sudo: required

notifications:
    email:
      on_success: never
      on_failure: change

branches:
  except:
    - staging.tmp

rust:
  - nightly

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

git:
  submodules: false

before_install:
  - sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash setup_mac_binutils.sh; fi
  - bash setup.sh

script:
  - cd kernel
  - RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build -q --target=bespin
  - bash run.sh
  - RUST_TEST_THREADS=1 cargo test --test integration-test