language: rust

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

branches:
  except:
    - staging.tmp

rust:
    - nightly

os:
  - linux
# Linker currently not working on OSX
# - osx

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - bash setup.sh

script:
  - cd kernel
  - RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build --target=bespin
  - bash run.sh