language: rust
sudo: false
notifications:
    email:
        on_success: never
        on_failure: change
branches:
  except:
    - staging.tmp
rust:
    - nightly
os:
  - linux
# Linker currently not working on OSX
# - osx
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

before_script:
  - bash -x setup.sh
  - git submodule init
  - git submodule update

script:
  - cd kernel && RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build --target=bespin