language: rust
sudo: required

notifications:
    email:
      on_success: never
      on_failure: change

branches:
  except:
    - staging.tmp
    - trying.tmp

rust:
  - nightly

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target
    - $TRAVIS_BUILD_DIR/binutils-2.30.90

git:
  submodules: false

before_install:
  - sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash setup_mac_binutils.sh; fi
  - bash setup.sh

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

script:
  - cd kernel
  - RUSTFLAGS="-D warnings" RUST_TARGET_PATH=`pwd`/src/arch/x86_64 xargo build -q --target=bespin
  - RUSTFLAGS="-D warnings" bash run.sh
  - cargo +nightly fmt --version
  - cargo +nightly fmt --package bespin -- --check
  - RUSTFLAGS="-D warnings" RUST_TEST_THREADS=1 cargo test --test integration-test
  - cd ../doc && mdbook build
  - bash deploy.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cd .. && bash deploy.sh
