[workspace]

members = [
    "kernel",
    #"bootloader",
    "lib/backtracer",
    "lib/x86",
    "lib/slabmalloc",
    "lib/klogger",
    "lib/elfloader",
    "lib/processor-trace",
    "lib/termcodes",
    "lib/libfringe"
]
