[workspace]

members = [
    "kernel",
    #"bootloader",
    "lib/backtracer",
    "lib/x86",
    "lib/slabmalloc",
    "lib/klogger",
    "lib/elfloader",
    "lib/processortrace",
    "lib/termcodes",
    "lib/libfringe"
]

# disable stack unwinding on panic for now
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
