[workspace]

resolver = "2"

members = [
    "kernel",
    "bootloader",
    "lib/backtracer",
    "lib/x86",
    "lib/slabmalloc",
    "lib/klogger",
    "lib/elfloader",
    #"lib/processortrace",
    "lib/termcodes",
    "lib/driverkit",
    "lib/apic",
    "lib/rumpkernel",
    "lib/linuxkernel",
    "lib/lineup",
    "lib/rawtime",
    "lib/ctest",
    "lib/custom_error",
    "lib/kpi",
    "lib/vibrio",
    "lib/topology",
    "lib/node-replication",
    "lib/mlnr",
    "lib/crossbeam-queue",
    "lib/bootloader_shared",
    "usr/init",
    "usr/rkapps",
]

# disable stack unwinding on panic for now
[profile.dev]
panic = "abort"
debug = true

[profile.release]
panic = "abort"
debug = true
