[workspace]

members = [
    "kernel",
    "bootloader",
    "lib/backtracer",
    "lib/x86",
    "lib/slabmalloc",
    "lib/klogger",
    "lib/elfloader",
    #"lib/processortrace",
    "lib/termcodes",
    "lib/driverkit",
    "lib/apic",
    "lib/rumpkernel",
    "lib/linuxkernel",
    "lib/lineup",
    "lib/rawtime",
    "lib/ctest",
    "lib/custom_error",
    "usr/init",
    "lib/kpi"
]

# disable stack unwinding on panic for now
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
