[package]
name = "init"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = { version = "0.4.8", default_features = false }
log = "0.4"
lineup = { path = "../../lib/lineup" }
rawtime = { path = "../../lib/rawtime" }
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false }

[dependencies.vibrio]
path = "../../lib/vibrio"
features = ["rumprt"]

[[bin]]
name = "init"
path = "src/init.rs"

