[package]
name = "init"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
edition = "2018"

[profile.debug]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
kpi = { path = "../../lib/kpi" }
slabmalloc = { path = "../../lib/slabmalloc" }
spin = { version = "0.4.8", default_features = false }
rlibc = { path = "../../lib/rlib" }

[[bin]]
name = "init"
path = "src/init.rs"

[build-dependencies]
cc = "1.0"
