[package]
name = "init"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "init"
path = "src/init.rs"

[dependencies]
spin = { version = "0.5.2", default_features = false }
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false }
log = "0.4"
lineup = { path = "../../lib/lineup" }
rawtime = { path = "../../lib/rawtime" }
x86 = { path = "../../lib/x86" }
vibrio = { path = "../../lib/vibrio" }
libm = "0.2.1"
lazy_static =  { version = "1.4", default_features = false }

[features]
rumprt = ["vibrio/rumprt"]
default = ["rumprt"]
# Use virtio instead of e1000
virtio = []

# Tests we run with CI make sure that the base features of
# the kernel are working:
test-print = []
test-map = []
test-alloc = []
test-upcall = []
test-scheduler = []
test-scheduler-smp = []
test-rump-tmpfs = [ "rumprt" ]
test-rump-net = [ "rumprt" ]
test-fs = []

# Simple micro-benchmarks
bench-vmops = []
bench-vmops-unmap = []
bench-vmops-unmaplat = []
fs-write = []
fxmark = []

# smoke: A way to tell the micro-benchmarks
# to only run for a short period, don't consume many
# resources, just enough to make sure they work
# but won't produce valid results
smoke = []
# Do latency measurements in benchmarks
latency = []
