[package]
name = "init"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
edition = "2018"

[profile.debug]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
spin = { version = "0.4.8", default_features = false }
log = "0.4"
vibrio = { path = "../../lib/vibrio" }
lineup = { path = "../../lib/lineup" }

[[bin]]
name = "init"
path = "src/init.rs"

