[package]
name = "bespin"
version = "0.0.1"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
]

description = "Experimental OS kernel"
readme = "README.md"
license = "MIT"

[dependencies]
x86 = { path = "../lib/x86" }
multiboot = { path = "../lib/multiboot" }
raw-cpuid = { path = "../lib/cpuid" }
rlibc = { path = "../lib/rlib" }
klogger = { path = "../lib/klogger" }
slabmalloc = { path = "../lib/slabmalloc" }
elfloader = { path = "../lib/elfloader" }
backtracer = { path = "../lib/backtracer/" }
apic = { path = "../lib/apic/" }
driverkit = { path = "../lib/driverkit/" }
lazy_static = { version = "1.1", features = ["nightly", "spin_no_std"] }
fringe = { path = "../lib/libfringe", default-features = false, features = ["alloc"] }
spin = "0.4.8"
log = "0.4"

[target.'cfg(not(target_os = "none"))'.dependencies]
libc = "*"

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
rexpect = "0.3"
matches = "0.1.8"

[features]
integration-tests = []
test-exit = []
test-pfault = []
test-gpfault = []
test-alloc = []
test-scheduler = []
test-sse = []