[package]
name = "bespin"
version = "0.0.1"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
]

description = "Experimental OS kernel"
readme = "README.md"
license = "MIT"
build = "build.rs"
edition = "2018"

[dependencies]
x86 = { path = "../lib/x86" }
multiboot = { path = "../lib/multiboot" }
raw-cpuid = { path = "../lib/cpuid" }
rlibc = { path = "../lib/rlib" }
klogger = { path = "../lib/klogger" }
slabmalloc = { path = "../lib/slabmalloc" }
elfloader = { path = "../lib/elfloader" }
backtracer = { path = "../lib/backtracer/" }
apic = { path = "../lib/apic/" }
driverkit = { path = "../lib/driverkit/" }
rumpkernel = { path = "../lib/rumpkernel" }
lineup = { path = "../lib/lineup" }
rawtime = { path = "../lib/rawtime" }
spin = "0.4"
log = "0.4"
lazy_static = { version = "1.2", features = ["nightly", "spin_no_std"] }
logos = { version = "0.9.7", default-features = false, features = ["export_derive"] }
# Some weirdness in Cargo dependency resolution currently pulls in libc so we use a patched cstr_core
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false }

[target.'cfg(not(target_os = "none"))'.dependencies]
libc = "0.2"

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
rexpect = "0.3"
matches = "0.1.8"

[features]
integration-tests = []
test-exit = []
test-pfault = []
test-gpfault = []
test-alloc = []
test-sse = []
test-rump-tmpfs = []
test-rump-net = []
test-time = []
test-scheduler = []
