[package]
name = "bespin"
version = "0.0.3"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
]

description = "Experimental OS kernel"
readme = "README.md"
license = "MIT"
build = "build.rs"
edition = "2018"

[dependencies]
# Our own dependencies:
x86 = { path = "../lib/x86" }
klogger = { path = "../lib/klogger" }
slabmalloc = { path = "../lib/slabmalloc" }
elfloader = { path = "../lib/elfloader" }
backtracer = { path = "../lib/backtracer/" }
apic = { path = "../lib/apic/" }
driverkit = { path = "../lib/driverkit/" }
rawtime = { path = "../lib/rawtime" }
custom_error = { path = "../lib/custom_error" }
topology = { path = "../lib/topology" }
node-replication = { path = "../lib/node-replication" }
mlnr = { path = "../lib/mlnr" }
kpi = { path = "../lib/kpi" }
bootloader_shared = { path = "../lib/bootloader_shared" }
# External libraries we use:
spin = "0.5.2"
log = "0.4"
arrayvec = { git = "https://github.com/gz/arrayvec.git", default-features = false, features = ["array-sizes-129-255"] }
lazy_static = { version = "1.3", features = ["spin_no_std"] }
logos = { version = "0.9.7", default-features = false, features = ["export_derive"] }
hashbrown = { version = "0.9.1", features = [ "nightly" ] }
crossbeam-queue = { path = "../lib/crossbeam-queue", default-features = false }
# Finally some external crates I forked due to issues with the current upstream version:
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false } # Some weirdness in Cargo dependency resolution currently pulls in libc so we use a patched cstr_core
acpica-sys = { git = "https://github.com/gz/acpica-sys.git" } # Need to upstream fixes
addr2line = { git = "https://github.com/gz/addr2line.git", branch = "patch-1", default-features = false, features = ["alloc", "rustc-demangle"] }
uefi = "0.6.0"
crossbeam-utils = { version = "0.8.0", default-features = false }
arr_macro = "0.1.3"
static_assertions = "1.1.0"

[[bin]]
name = "bespin"
path = "src/main.rs"

[target.'cfg(target_os = "none")'.dependencies]
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_cbor = { version = "0.11", default-features = false }

[target.'cfg(not(target_os = "none"))'.dependencies]
libc = { version = "0.2.53", default-features = false }
csv = "1.1"
serde = { version = "1" }
serde_cbor = { version = "0.11" }

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
rexpect = "0.3"
matches = "0.1.8"
proptest = "0.9.4"
env_logger = "*"
num_cpus = "1.12"

[build-dependencies]
cc = "1.0"

[features]
default = ["mlnrfs"]
# Use concurrent in-memory filesystem with mlnr.
mlnrfs = []
# Run an integration test instead of standard kernel main function
integration-test = []
# smoke: Shorten long running benchmarks to test just functionality
smoke = []
# pre-alloc guest memory: For serious benchmarking where we want to avoid VM exits as much as possible
prealloc = []
# Don't boot entire system. only initialize bsp core
bsp-only = []
# exit: test qemu exit functionality (used heavily for CI)
test-exit = ["integration-test", "bsp-only"]
# pfault-early: test page-fault handler early on during init
test-pfault-early = ["integration-test", "bsp-only"]
# gpfault-early: test general protection fault handler early on during init
test-gpfault-early = ["integration-test", "bsp-only"]
# pfault: test page-fault handler
test-pfault = ["integration-test", "bsp-only"]
# gpfault: test general protection fault handler
test-gpfault = ["integration-test", "bsp-only"]
# double_fault: test double fault handler
test-double-fault = ["integration-test", "bsp-only"]
# alloc: test memory allocation
test-alloc = ["integration-test", "bsp-only"]
# sse: test SIMD register are usable
test-sse = ["integration-test", "bsp-only"]
# test time
test-time = ["integration-test", "bsp-only"]
# test apic timer
test-timer = ["integration-test", "bsp-only"]
# acpi: test ACPI can initialize
test-acpi-smoke = [ "integration-test", "bsp-only" ]
# acpi: test ACPI with complex topology
test-acpi-topology = [ "integration-test", "bsp-only" ]
# coreboot_smoke: Test APIs to boot-up additional cores
test-coreboot-smoke = ["integration-test", "bsp-only" ]
# coreboot_nrlog: Test APIs to boot-up additional cores and communicate using nr
test-coreboot-nrlog = ["integration-test", "bsp-only" ]
# coreboot: Test core booting logic (during actual system initialization)
test-coreboot = ["integration-test" ]
# userspace: run a test in user-space by spawning the init process
test-userspace = ["integration-test", "bsp-only"]
# userspace_smp: Test that we can dispatch a process on multiple cores
test-userspace-smp = ["integration-test"]
# vspace_debug: print initial vspace in graphviz format
test-vspace-debug = ["integration-test", "bsp-only"]
