[package]
name = "bespin"
version = "0.0.1"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
]

description = "Experimental OS kernel"
readme = "README.md"
license = "MIT"
build = "build.rs"
edition = "2018"


[dependencies]
#test = { path = "../lib/ctest" }
x86 = { path = "../lib/x86" }
raw-cpuid = { path = "../lib/cpuid" }
klogger = { path = "../lib/klogger" }
slabmalloc = { path = "../lib/slabmalloc" }
elfloader = { path = "../lib/elfloader" }
backtracer = { path = "../lib/backtracer/" }
apic = { path = "../lib/apic/" }
driverkit = { path = "../lib/driverkit/" }
lineup = { path = "../lib/lineup", optional = true }
rawtime = { path = "../lib/rawtime" }
custom_error = { path = "../lib/custom_error" }
spin = "0.4"
log = "0.4"
lazy_static = { version = "1.3", features = ["spin_no_std"] }
logos = { version = "0.9.7", default-features = false, features = ["export_derive"] }
# Some weirdness in Cargo dependency resolution currently pulls in libc so we use a patched cstr_core
cstr_core = { git = "https://github.com/gz/cstr_core.git", default-features = false }
acpica-sys = { git = "https://github.com/gz/acpica-sys.git" }
uefi = { git = "https://github.com/rust-osdev/uefi-rs.git" }
addr2line = { git = "https://github.com/gz/addr2line.git", branch = "patch-1", default-features = false, features = ["alloc", "rustc-demangle"] }
kpi = { path = "../lib/kpi" }
topology = { path = "../lib/topology" }

[[bin]]
name = "bespin"
harness = false

[target.'cfg(not(target_os = "none"))'.dependencies]
libc = { version = "0.2.53", default-features = false }

[target.'cfg(not(target_os = "none"))'.dev-dependencies]
rexpect = "0.3"
matches = "0.1.8"

[build-dependencies]
cc = "1.0"

[features]
# Run an integration test instead of standard kernel main function
integration-test = []
# exit: test qemu exit functionality (used heavily for CI)
test-exit = ["integration-test"]
# pfault: test page-fault handler
test-pfault = ["integration-test"]
# gpfault: test general protection fault handler
test-gpfault = ["integration-test"]
# alloc: test memory allocation
test-alloc = ["integration-test"]
# sse: test SIMD register are usable
test-sse = ["integration-test"]
# test time
test-time = ["integration-test"]
# scheduler: test cooperative scheduler
test-scheduler = [ "integration-test", "lineup" ]
# acpi: test ACPI can initialize
test-acpi-smoke = [ "integration-test" ]
# acpi: test ACPI with complex topology
test-acpi-topology = [ "integration-test" ]
# coreboot: Test that we can boot-up additional cores
test-coreboot = ["integration-test", "lineup" ]
# userspace: run a test in user-space by spawning the init process
test-userspace = ["integration-test"]
