[package]
name = "bespin"
version = "0.0.1"
authors = [
  "Gerd Zellweger <mail@gerdzellweger.com>",
]

description = "Experimental OS kernel"
readme = "README.md"
license = "MIT"

[lib]
crate-type = ["staticlib"]

[features]
integration-tests = []
test-exit = []
test-pfault = []
test-gpfault = []
test-alloc = []
test-scheduler = []

# disable stack unwinding on panic for now
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
x86 = { path = "../lib/x86" }
multiboot = { path = "../lib/multiboot" }
raw-cpuid = { path = "../lib/cpuid" }
rlibc = { path = "../lib/rlib" }
klogger = { path = "../lib/klogger" }
slabmalloc = { path = "../lib/slabmalloc" }
elfloader = { path = "../lib/elfloader" }
backtracer = { path = "../lib/backtracer/" }
#termstyle = { path = "../lib/termstyle" }
lazy_static = { version = "1.1", features = ["nightly", "spin_no_std"] }
spin = "0.4.8"
log = "0.4"

[dependencies.fringe]
path = "../lib/libfringe/"
no-default-features = true

[dev-dependencies]
rexpect = "0.3"
matches = "0.1.8"

[[test]]
name = "integration-test"
path = "tests/integration-test.rs"
