[package]
name = "bootloader"
version = "0.0.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
uefi = { version = "0.3.2", features = ["exts"] }
uefi-services = { version = "0.1.0" }
log = { version = "0.4", default-features = false }
elfloader = { path = "../lib/elfloader" }
x86 = { path = "../lib/x86" }